// ------------------------------------------------------------------------------
// <auto-generated>
// Este código fue generado por una herramienta.
// Versión de runtime:4.0.30319.42000
// 
// Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
// se vuelve a generar el código.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using System.Drawing;
using Microsoft.VisualBasic;

namespace AplicacionPeliculas.My.Resources
{

    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    /// <summary>
    /// Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("AplicacionPeliculas.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        /// búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _1_83_icon_icons_com_68859
        {
            get
            {
                var obj = ResourceManager.GetObject("1-83_icon-icons.com_68859", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _17_104874
        {
            get
            {
                var obj = ResourceManager.GetObject("17_104874", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _27_Edit_Text_256x256_35395
        {
            get
            {
                var obj = ResourceManager.GetObject("27-Edit_Text_256x256_35395", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap _3643769_building_home_house_main_menu_start_113416
        {
            get
            {
                var obj = ResourceManager.GetObject("3643769-building-home-house-main-menu-start_113416", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap add_icon_icons_com_74429
        {
            get
            {
                var obj = ResourceManager.GetObject("add_icon-icons.com_74429", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Add_Image_icon_icons_com_54218
        {
            get
            {
                var obj = ResourceManager.GetObject("Add_Image_icon-icons.com_54218", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap adduser_105070
        {
            get
            {
                var obj = ResourceManager.GetObject("adduser_105070", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap administrator_3552
        {
            get
            {
                var obj = ResourceManager.GetObject("administrator_3552", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap choose_2_102347
        {
            get
            {
                var obj = ResourceManager.GetObject("choose-2_102347", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap choose_2_1023471
        {
            get
            {
                var obj = ResourceManager.GetObject("choose-2_1023471", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Cuenta
        {
            get
            {
                var obj = ResourceManager.GetObject("Cuenta", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap cuenta1
        {
            get
            {
                var obj = ResourceManager.GetObject("cuenta1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap delete_40623
        {
            get
            {
                var obj = ResourceManager.GetObject("delete_40623", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Diapositiva1
        {
            get
            {
                var obj = ResourceManager.GetObject("Diapositiva1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap edituser_105124
        {
            get
            {
                var obj = ResourceManager.GetObject("edituser_105124", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap fondo
        {
            get
            {
                var obj = ResourceManager.GetObject("fondo", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap fondo2
        {
            get
            {
                var obj = ResourceManager.GetObject("fondo2", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap fondo3
        {
            get
            {
                var obj = ResourceManager.GetObject("fondo3", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap fondo4
        {
            get
            {
                var obj = ResourceManager.GetObject("fondo4", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap garbage_trash_bin_delete_icon_219499
        {
            get
            {
                var obj = ResourceManager.GetObject("garbage_trash_bin_delete_icon_219499", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap loupe_79257
        {
            get
            {
                var obj = ResourceManager.GetObject("loupe_79257", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Peliculasss
        {
            get
            {
                var obj = ResourceManager.GetObject("Peliculasss", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap user_man_delete_21957
        {
            get
            {
                var obj = ResourceManager.GetObject("user_man_delete_21957", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap UserAdd_40960
        {
            get
            {
                var obj = ResourceManager.GetObject("UserAdd_40960", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap UserEdit_40958
        {
            get
            {
                var obj = ResourceManager.GetObject("UserEdit_40958", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap UserRemove_40959
        {
            get
            {
                var obj = ResourceManager.GetObject("UserRemove_40959", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap vote_counting_magnifier_icon_154141
        {
            get
            {
                var obj = ResourceManager.GetObject("vote_counting_magnifier_icon_154141", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}